apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secrets.yaml
  - configmap.yaml

commonLabels:
  app: book-management
  environment: production

namespace: book-management 