apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  # Base64 encoded value for mongodb+srv://i222724:CALLOFDUTY@cluster0.cry11.mongodb.net/bookmanagement
  uri: bW9uZ29kYitzcnY6Ly9pMjIyNzI0OkNBTExPRkRVVFlAY2x1c3RlcjAuY3J5MTEubW9uZ29kYi5uZXQvYm9va21hbmFnZW1lbnQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # Base64 encoded value for yoursecretkey123456
  token: eW91cnNlY3JldGtleTEyMzQ1Ng== 