apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: book-management
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: book-management
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: book-management
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: book-management
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: book-management
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: book-management
    tier: database 